<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RollGrinder.Integration.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RollGrinder.Composition\RollGrinder.Composition.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Core\RollGrinder.Core.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Sim\RollGrinder.Sim.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Services\RollGrinder.Services.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Data\RollGrinder.Data.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Device\RollGrinder.Device.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Contracts\RollGrinder.Contracts.csproj" />
    <ProjectReference Include="..\..\src\RollGrinder.Device\RollGrinder.Device.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
